#!/bin/bash

# This file should only be run once as an initialisation of the project, or when the author list is updated.
# This file should be run from the root of the paper git repo. The call is track_changes/set_author_info_color.sh

declare -a colors=('red' 'blue' 'green' 'orange' 'pink' 'violet' 'teal' 'cyan' 'yellow' 'magenta' 'gray')

MYAUTHORCOLORS=my_author_colors.tex
AUTHORCOLORS=author_colors.tex
AUTHORINFO=author_info.tex
COLORCHANGE=color_change.tex

rm -rf $AUTHORCOLORS
rm -rf $AUTHORINFO
rm -rf $COLORCHANGE

echo 'Running author_personalisations: '

. ./user_config.sh

cd $paper_path

echo 'Changed into ' $paper_path

if [ ! -e $MYAUTHORCOLORS ]
then
  echo '%% This file is automatically generated and recreated each time track_changes/set_author_info_color.sh is run' >> $AUTHORCOLORS
  echo '' >> $AUTHORCOLORS
  echo '% This file sets the colors for the authors. This file is called by "author_info.tex"' >> $AUTHORCOLORS
  echo '% In this automatically generated file, the author colors are set to default values.' >> $AUTHORCOLORS
  echo '% IMPORTANT: If you want to create your own colors, i) copy this file, ii) rename it "my_author_colors.tex" and iii) modify the colors."' >> $AUTHORCOLORS
  echo '% The file "my_author_colors.tex" is not removed  when rerunning track_changes/set_author_info_color.sh' >> $AUTHORCOLORS
  
  count=0
  for author in "${author_list[@]}"
  do
    echo "\newcommand{\colour${author^}}{${colors[count]}}" >> $AUTHORCOLORS
      
    count=$(( $count + 1 ))
  done

  echo '' >> $AUTHORCOLORS
  echo '' >> $AUTHORCOLORS
  echo '%% Examples of different colors that can be put into "my_author_colors.tex".' >> $AUTHORCOLORS
  echo '%%author colours see http://htmlcolorcodes.com/color-chart/' >> $AUTHORCOLORS
  echo '%\newcommand{\colourPenny}{orange}' >> $AUTHORCOLORS
  echo '%\definecolor{navy}{HTML}{000080} ' >> $AUTHORCOLORS
  echo '%\newcommand{\colourSteve}{navy}' >> $AUTHORCOLORS
fi

# Creating the general author_info file. This contains the commands 
echo '%% This file provides the author personalisations for the different authors.' >> $AUTHORINFO
echo '%% The first half of this file is general for all projects.' >> $AUTHORINFO
echo '%% The second half is project specific and describes the different authors.' >> $AUTHORINFO
echo '%% If the author list changes, then update the second half or rerun the script track_changes/set_author_info_color.sh' >> $AUTHORINFO
echo '%% NOTE: Any changes to the author list requires a change to the user_config.sh' >> $AUTHORINFO
echo '' >> $AUTHORINFO
echo '' >> $AUTHORINFO

echo '% Checking whether "my_author_colors.tex" exists and if so, input it.' >> $AUTHORINFO
echo '\IfFileExists{my_author_colors.tex}' >> $AUTHORINFO
echo '{' >> $AUTHORINFO
echo '  \include{my_author_colors}' >> $AUTHORINFO
echo '}' >> $AUTHORINFO
echo '{' >> $AUTHORINFO
echo '  \include{author_colors}' >> $AUTHORINFO
echo '}' >> $AUTHORINFO
echo '' >> $AUTHORINFO
echo '' >> $AUTHORINFO
echo '' >> $AUTHORINFO

echo '\NewDocumentCommand{\newauthor}{mmm}{' >> $AUTHORINFO
echo '        \expandafter\NewDocumentCommand\csname #1\endcsname{#2}{' >> $AUTHORINFO
echo '{{\setstretch{0.7}\todo[linecolor=\csname colour#1\endcsname,backgroundcolor=\csname colour#1\endcsname!25,bordercolor=\csname colour#1\endcsname,size=\scriptsize]{\textbf{#1} #3}}}}' >> $AUTHORINFO
echo '}' >> $AUTHORINFO


# Adding personal info for the author names. The created file (author_info_names.tex) will be input into author_info.tex
echo '%% NOTE: Edit from here for different personalisations. Remember that this file is regenerated each time track_changes/set_author_info_color.sh is run' >> $AUTHORINFO
echo '% This file is the individual personalisations for the author info.' >> $AUTHORINFO
echo '' >> $AUTHORINFO
echo '' >> $AUTHORINFO

echo '%Assign \colourauthor based on \currentauthor as defined in .tex' >> $AUTHORINFO
for author in "${author_list[@]}"
do  
  echo "\\ifcase\\pdfstrcmp{\\currentauthor}{${author^}}\\newcommand{\\colourauthor}{\\colour${author^}}\\fi" >> $AUTHORINFO
  echo "\\newauthor{${author^}}{mm}{\\textbf{#1:}~#2}" >> $AUTHORINFO
  echo '' >> $AUTHORINFO
done



# Creating the color change file. This file controls the color changes for each of the authors
echo '%% This file is automatically generated from the track_changes/set_author_info_colors.sh script' >> $COLORCHANGE
echo '' >> $COLORCHANGE
echo '%% This file is in two parts.' >> $COLORCHANGE
echo '%% The first is the general components for the latex diff commands' >> $COLORCHANGE
echo '%% The second part contains personalisations. You can update the second part.' >> $COLORCHANGE
echo '%% NOTE: This file will be deleted and regenerated when track_changes/set_author_info_colors.sh is called' >> $COLORCHANGE
echo '' >> $COLORCHANGE
echo '' >> $COLORCHANGE
echo '\RequirePackage[normalem]{ulem} %DIF PREAMBLE' >> $COLORCHANGE
echo '%\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE' >> $COLORCHANGE

echo '%generic' >> $COLORCHANGE
echo '\providecommand{\DIFadd}[1]{{\protect\color{\colourauthor}\uwave{#1}}} %DIF PREAMBLE' >> $COLORCHANGE
echo '\providecommand{\DIFdel}[1]{{\protect\color{\colourauthor}\sout{#1}}}  %DIF PREAMBLE' >> $COLORCHANGE

echo '%DIF SAFE PREAMBLE %DIF PREAMBLE' >> $COLORCHANGE
echo '\providecommand{\DIFaddbegin}{} %DIF PREAMBLE' >> $COLORCHANGE
echo '\providecommand{\DIFaddend}{} %DIF PREAMBLE' >> $COLORCHANGE
echo '\providecommand{\DIFdelbegin}{} %DIF PREAMBLE' >> $COLORCHANGE
echo '\providecommand{\DIFdelend}{} %DIF PREAMBLE' >> $COLORCHANGE


# Adding personal info for the color changes. The created file (color_change_names.tex) will be input into color_change.tex
echo '% This is the second part that contains the individual personalisations for the color change.' >> $COLORCHANGE
echo '' >> $COLORCHANGE
echo '' >> $COLORCHANGE

echo '%author specific' >> $COLORCHANGE
for author in "${author_list[@]}"
do  
  echo "\\providecommand{\\DIFadd${author^}}[1]{{\\protect\\color{\\colour${author^}}\\uwave{#1}}} %DIF PREAMBLE" >> $COLORCHANGE
  echo "\\providecommand{\\DIFdel${author^}}[1]{{\\protect\\color{\\colour${author^}}\\sout{#1}}}  %DIF PREAMBLE" >> $COLORCHANGE
  echo '' >> $COLORCHANGE
done


exit
